version: '3.9'

services:
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6381:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass Bl0g4dm1n
    volumes:
      - ~/apps/redis:/var/lib/redis/data
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Bl0g4dm1n
      - POSTGRES_USER=blogadmin
      - POSTGRES_DB=blog_db